### ISSUE TITLE
Build Inventory Fails When Device Has No Platform Assigned

### ISSUE THREAD

**Issue by gmoisio** [nautobot/nornir-nautobot#20]
Hi all.

In the Build Inventory method of nornir-nautobot we can see:

`host_platform=device.platform.slug`

But looking at Nautobot 1.0, it is something more like:

`host_platform=device.device_type.manufacturer.slug`

That is working fine...

Thanks
Regards

**Comment by jvanderaa** [comment]
`host_platform` is intended to get the connection for the device, for such things as using NAPALM or Netmiko. This should correspond to the device platform, such as `cisco_ios` rather than the manufacturer that would just get `cisco`. I'm not sure what the issue presented is otherwise. Let us know.

**Comment by gmoisio** [comment]
Keeping `host_platform=device.platform.slug` I get this error: `AttributeError: 'NoneType' object has no attribute 'slug'`

I'm using Nautobot 1.0, nornir==3.1.1, nornir-nautobot==2.0.0 and Python 3.9.5

Thanks

**Comment by jvanderaa** [comment]
Thanks. That makes sense what is happening. The device inside of Nautobot has no platform assigned. In which case the end result is `None`, but there is an error happening.

**Comment by gmoisio** [comment]
For your information, using the same Nautobot database with Ansible collection networktocode.nautobot, there is no issue.
Thanks
