### ISSUE TITLE
Allow connection through proxy SOCKS

### ISSUE THREAD

**Issue by Never77** [nautobot/nornir-nautobot#38]
It's impossible for now to connect to a device through a proxy SOCKS or any bastion server, would be possible to add this feature ?

**Comment by itdependsnetworks** [comment]
Under the hood, for connecting to devices, we leverage napalm or netmiko. They would have to support proxy SOCKS first. I do not believe that they currently do. Will leave ticket open for another week in case I am misunderstanding.
