### ISSUE TITLE
netmiko 4 causes the dispatcher to fail

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nornir-nautobot#55]
Multiple users have had issues where the import statements need to be updated in dispatcher/default.py.

From:
```
from netmiko.ssh_exception import NetmikoAuthenticationException, NetmikoTimeoutException
```

To:
```
from netmiko import NetmikoAuthenticationException, NetmikoTimeoutException
```

**Comment by jeffkala** [comment]
[Netmiko 4.0.0 Release](https://github.com/ktbyers/netmiko/releases/tag/v4.0.0)

**Comment by jeffkala** [comment]
Users environment was set at
```
napalm==3.3.1
nornir-napalm==0.2.0
netmiko==4.1.1
nornir-netmiko==0.2.0
```

**Comment by mzbroch** [comment]
@jvanderaa We need to downgrade nornir-netmiko to 0.1.2 - current 0* impacts other plugin and builds.

**Comment by jvanderaa** [comment]
@mzbroch does https://github.com/nautobot/nornir-nautobot/pull/56 fix this? Please try with the `develop` branch.

I would like to not have a PR that pins/downgrades code. The other plugins should move forward and update rather than require a library to pin and possibly get stale.

**Comment by jvanderaa** [comment]
@jeffkala does develop work based on #56

**Comment by jeffkala** [comment]
@qduk can you validate this fixed the problem in the environment you were testing?

**Comment by mzbroch** [comment]
This is fair, however... This package dependency went in uncontrolled, because of lack of a proper pinning.

**Comment by jvanderaa** [comment]
The `0*` is something that as the library we decided would be good to keep up to date. Should we look to move to a `*` instead? I would not expect to pin at `0.1.2`. That would then cause downstream effects from the project dependencies, not allowing for apps to leverage new versions of Netmiko and the inventory plugin.

**Comment by jvanderaa** [comment]
This is confirmed fixed in develop.
