### ISSUE TITLE
Bump the verison for nornir-netmiko to use the new release ?

### ISSUE THREAD

**Issue by muffi-dn** [nautobot/nornir-nautobot#92]
Currently the nornir-netmiko version is restricted to `>=0.0.0 <0.1.0` while the latest version available is `1.0.0`. I can raise a PR to update the pyproject.toml and the lock file if there is an agreement.

**Comment by jvanderaa** [comment]
Agreed @muffi-dn! I'm recalling now that Netmiko did move to the 1.0.0 versioning on that, which is going to be very helpful for the versioning controls.

**Comment by muffi-dn** [comment]
Raised a PR: https://github.com/nautobot/nornir-nautobot/pull/93
